// OWNER: AI-02 (generated by ffigen from src/vw_whisper.h; do not edit)
// ignore_for_file: type=lint, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// Bindings for src/vw_whisper.h (C ABI version 1). Generated; do not edit.
///
class VwWhisperBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  VwWhisperBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  VwWhisperBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// library
  int vw_abi_version() {
    return _vw_abi_version();
  }

  late final _vw_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('vw_abi_version');
  late final _vw_abi_version = _vw_abi_versionPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> vw_engine_version() {
    return _vw_engine_version();
  }

  late final _vw_engine_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'vw_engine_version');
  late final _vw_engine_version =
      _vw_engine_versionPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  ffi.Pointer<ffi.Char> vw_system_info() {
    return _vw_system_info();
  }

  late final _vw_system_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'vw_system_info');
  late final _vw_system_info =
      _vw_system_infoPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();

  int vw_cpu_features() {
    return _vw_cpu_features();
  }

  late final _vw_cpu_featuresPtr =
      _lookup<ffi.NativeFunction<ffi.Uint64 Function()>>('vw_cpu_features');
  late final _vw_cpu_features =
      _vw_cpu_featuresPtr.asFunction<int Function()>();

  int vw_perf_core_count() {
    return _vw_perf_core_count();
  }

  late final _vw_perf_core_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('vw_perf_core_count');
  late final _vw_perf_core_count =
      _vw_perf_core_countPtr.asFunction<int Function()>();

  void vw_set_log_level(
    int level,
  ) {
    return _vw_set_log_level(
      level,
    );
  }

  late final _vw_set_log_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int32)>>(
          'vw_set_log_level');
  late final _vw_set_log_level =
      _vw_set_log_levelPtr.asFunction<void Function(int)>();

  int vw_lang_max_id() {
    return _vw_lang_max_id();
  }

  late final _vw_lang_max_idPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('vw_lang_max_id');
  late final _vw_lang_max_id = _vw_lang_max_idPtr.asFunction<int Function()>();

  ffi.Pointer<ffi.Char> vw_lang_code(
    int id,
  ) {
    return _vw_lang_code(
      id,
    );
  }

  late final _vw_lang_codePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Int32)>>(
          'vw_lang_code');
  late final _vw_lang_code =
      _vw_lang_codePtr.asFunction<ffi.Pointer<ffi.Char> Function(int)>();

  void vw_shutdown_all() {
    return _vw_shutdown_all();
  }

  late final _vw_shutdown_allPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('vw_shutdown_all');
  late final _vw_shutdown_all =
      _vw_shutdown_allPtr.asFunction<void Function()>();

  void vw_free(
    ffi.Pointer<ffi.Void> p,
  ) {
    return _vw_free(
      p,
    );
  }

  late final _vw_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'vw_free');
  late final _vw_free =
      _vw_freePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// model
  ffi.Pointer<vw_model> vw_model_load(
    ffi.Pointer<ffi.Char> model_path,
    ffi.Pointer<vw_model_params> params,
  ) {
    return _vw_model_load(
      model_path,
      params,
    );
  }

  late final _vw_model_loadPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<vw_model> Function(ffi.Pointer<ffi.Char>,
              ffi.Pointer<vw_model_params>)>>('vw_model_load');
  late final _vw_model_load = _vw_model_loadPtr.asFunction<
      ffi.Pointer<vw_model> Function(
          ffi.Pointer<ffi.Char>, ffi.Pointer<vw_model_params>)>();

  int vw_model_get_state(
    ffi.Pointer<vw_model> m,
  ) {
    return _vw_model_get_state(
      m,
    );
  }

  late final _vw_model_get_statePtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<vw_model>)>>(
          'vw_model_get_state');
  late final _vw_model_get_state =
      _vw_model_get_statePtr.asFunction<int Function(ffi.Pointer<vw_model>)>();

  int vw_model_error(
    ffi.Pointer<vw_model> m,
    ffi.Pointer<ffi.Char> buf,
    int buf_len,
  ) {
    return _vw_model_error(
      m,
      buf,
      buf_len,
    );
  }

  late final _vw_model_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<vw_model>, ffi.Pointer<ffi.Char>,
              ffi.Int32)>>('vw_model_error');
  late final _vw_model_error = _vw_model_errorPtr.asFunction<
      int Function(ffi.Pointer<vw_model>, ffi.Pointer<ffi.Char>, int)>();

  int vw_model_info_get(
    ffi.Pointer<vw_model> m,
    ffi.Pointer<vw_model_info> out,
  ) {
    return _vw_model_info_get(
      m,
      out,
    );
  }

  late final _vw_model_info_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<vw_model>,
              ffi.Pointer<vw_model_info>)>>('vw_model_info_get');
  late final _vw_model_info_get = _vw_model_info_getPtr.asFunction<
      int Function(ffi.Pointer<vw_model>, ffi.Pointer<vw_model_info>)>();

  void vw_model_release(
    ffi.Pointer<vw_model> m,
  ) {
    return _vw_model_release(
      m,
    );
  }

  late final _vw_model_releasePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<vw_model>)>>(
          'vw_model_release');
  late final _vw_model_release =
      _vw_model_releasePtr.asFunction<void Function(ffi.Pointer<vw_model>)>();

  /// job: at most one active job per model (VW_ERR_BUSY otherwise)
  ffi.Pointer<vw_job> vw_job_start(
    ffi.Pointer<vw_model> m,
    ffi.Pointer<vw_job_params> params,
    ffi.Pointer<ffi.Int32> out_status,
  ) {
    return _vw_job_start(
      m,
      params,
      out_status,
    );
  }

  late final _vw_job_startPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<vw_job> Function(
              ffi.Pointer<vw_model>,
              ffi.Pointer<vw_job_params>,
              ffi.Pointer<ffi.Int32>)>>('vw_job_start');
  late final _vw_job_start = _vw_job_startPtr.asFunction<
      ffi.Pointer<vw_job> Function(ffi.Pointer<vw_model>,
          ffi.Pointer<vw_job_params>, ffi.Pointer<ffi.Int32>)>();

  void vw_job_status_get(
    ffi.Pointer<vw_job> j,
    ffi.Pointer<vw_job_status> out,
  ) {
    return _vw_job_status_get(
      j,
      out,
    );
  }

  late final _vw_job_status_getPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<vw_job>,
              ffi.Pointer<vw_job_status>)>>('vw_job_status_get');
  late final _vw_job_status_get = _vw_job_status_getPtr.asFunction<
      void Function(ffi.Pointer<vw_job>, ffi.Pointer<vw_job_status>)>();

  ffi.Pointer<ffi.Char> vw_job_take_segments_json(
    ffi.Pointer<vw_job> j,
    int from_index,
    int max_count,
  ) {
    return _vw_job_take_segments_json(
      j,
      from_index,
      max_count,
    );
  }

  late final _vw_job_take_segments_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<vw_job>, ffi.Int32,
              ffi.Int32)>>('vw_job_take_segments_json');
  late final _vw_job_take_segments_json =
      _vw_job_take_segments_jsonPtr.asFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<vw_job>, int, int)>();

  ffi.Pointer<ffi.Char> vw_job_language_probs_json(
    ffi.Pointer<vw_job> j,
    int top_n,
  ) {
    return _vw_job_language_probs_json(
      j,
      top_n,
    );
  }

  late final _vw_job_language_probs_jsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(
              ffi.Pointer<vw_job>, ffi.Int32)>>('vw_job_language_probs_json');
  late final _vw_job_language_probs_json = _vw_job_language_probs_jsonPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<vw_job>, int)>();

  void vw_job_cancel(
    ffi.Pointer<vw_job> j,
  ) {
    return _vw_job_cancel(
      j,
    );
  }

  late final _vw_job_cancelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<vw_job>)>>(
          'vw_job_cancel');
  late final _vw_job_cancel =
      _vw_job_cancelPtr.asFunction<void Function(ffi.Pointer<vw_job>)>();

  void vw_job_pause(
    ffi.Pointer<vw_job> j,
    int abort_current_chunk,
  ) {
    return _vw_job_pause(
      j,
      abort_current_chunk,
    );
  }

  late final _vw_job_pausePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<vw_job>, ffi.Int32)>>('vw_job_pause');
  late final _vw_job_pause =
      _vw_job_pausePtr.asFunction<void Function(ffi.Pointer<vw_job>, int)>();

  void vw_job_resume(
    ffi.Pointer<vw_job> j,
  ) {
    return _vw_job_resume(
      j,
    );
  }

  late final _vw_job_resumePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<vw_job>)>>(
          'vw_job_resume');
  late final _vw_job_resume =
      _vw_job_resumePtr.asFunction<void Function(ffi.Pointer<vw_job>)>();

  void vw_job_set_threads(
    ffi.Pointer<vw_job> j,
    int n_threads,
  ) {
    return _vw_job_set_threads(
      j,
      n_threads,
    );
  }

  late final _vw_job_set_threadsPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<vw_job>, ffi.Int32)>>(
      'vw_job_set_threads');
  late final _vw_job_set_threads = _vw_job_set_threadsPtr
      .asFunction<void Function(ffi.Pointer<vw_job>, int)>();

  void vw_job_free(
    ffi.Pointer<vw_job> j,
  ) {
    return _vw_job_free(
      j,
    );
  }

  late final _vw_job_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<vw_job>)>>(
          'vw_job_free');
  late final _vw_job_free =
      _vw_job_freePtr.asFunction<void Function(ffi.Pointer<vw_job>)>();
}

enum vw_status {
  VW_OK(0),
  VW_ERR_INVALID_ARG(1),
  VW_ERR_MODEL_LOAD(2),
  VW_ERR_WAV_FORMAT(3),
  VW_ERR_IO(4),
  VW_ERR_OOM(5),
  VW_ERR_CANCELLED(6),
  VW_ERR_INFERENCE(7),
  VW_ERR_BUSY(8),
  VW_ERR_VAD_MODEL(9),
  VW_ERR_NO_SPEECH(10),
  VW_ERR_INTERNAL(99);

  final int value;
  const vw_status(this.value);

  static vw_status fromValue(int value) => switch (value) {
        0 => VW_OK,
        1 => VW_ERR_INVALID_ARG,
        2 => VW_ERR_MODEL_LOAD,
        3 => VW_ERR_WAV_FORMAT,
        4 => VW_ERR_IO,
        5 => VW_ERR_OOM,
        6 => VW_ERR_CANCELLED,
        7 => VW_ERR_INFERENCE,
        8 => VW_ERR_BUSY,
        9 => VW_ERR_VAD_MODEL,
        10 => VW_ERR_NO_SPEECH,
        99 => VW_ERR_INTERNAL,
        _ => throw ArgumentError('Unknown value for vw_status: $value'),
      };
}

enum vw_model_state {
  VW_MODEL_LOADING(0),
  VW_MODEL_READY(1),
  VW_MODEL_FAILED(2);

  final int value;
  const vw_model_state(this.value);

  static vw_model_state fromValue(int value) => switch (value) {
        0 => VW_MODEL_LOADING,
        1 => VW_MODEL_READY,
        2 => VW_MODEL_FAILED,
        _ => throw ArgumentError('Unknown value for vw_model_state: $value'),
      };
}

enum vw_job_state {
  VW_JOB_RUNNING(1),
  VW_JOB_PAUSED(2),
  VW_JOB_SUCCEEDED(3),
  VW_JOB_FAILED(4),
  VW_JOB_CANCELLED(5);

  final int value;
  const vw_job_state(this.value);

  static vw_job_state fromValue(int value) => switch (value) {
        1 => VW_JOB_RUNNING,
        2 => VW_JOB_PAUSED,
        3 => VW_JOB_SUCCEEDED,
        4 => VW_JOB_FAILED,
        5 => VW_JOB_CANCELLED,
        _ => throw ArgumentError('Unknown value for vw_job_state: $value'),
      };
}

enum vw_job_mode {
  VW_MODE_TRANSCRIBE(0),
  VW_MODE_DETECT_LANGUAGE(1);

  final int value;
  const vw_job_mode(this.value);

  static vw_job_mode fromValue(int value) => switch (value) {
        0 => VW_MODE_TRANSCRIBE,
        1 => VW_MODE_DETECT_LANGUAGE,
        _ => throw ArgumentError('Unknown value for vw_job_mode: $value'),
      };
}

enum vw_phase {
  VW_PHASE_PREPARING(0),
  VW_PHASE_VAD(1),
  VW_PHASE_ENCODING(2),
  VW_PHASE_DECODING(3);

  final int value;
  const vw_phase(this.value);

  static vw_phase fromValue(int value) => switch (value) {
        0 => VW_PHASE_PREPARING,
        1 => VW_PHASE_VAD,
        2 => VW_PHASE_ENCODING,
        3 => VW_PHASE_DECODING,
        _ => throw ArgumentError('Unknown value for vw_phase: $value'),
      };
}

final class vw_model extends ffi.Opaque {}

final class vw_job extends ffi.Opaque {}

final class vw_model_params extends ffi.Struct {
  @ffi.Int32()
  external int struct_size;

  /// request; the shim applies the iOS GPU policy and may downgrade
  @ffi.Int32()
  external int use_gpu;

  /// 1 (default)
  @ffi.Int32()
  external int flash_attn;

  /// 0 = off (default); else whisper_alignment_heads_preset; forces flash_attn = 0
  @ffi.Int32()
  external int dtw_preset;
}

final class vw_model_info extends ffi.Struct {
  @ffi.Int32()
  external int struct_size;

  @ffi.Int32()
  external int multilingual;

  @ffi.Int32()
  external int n_vocab;

  @ffi.Int32()
  external int model_type;

  @ffi.Int32()
  external int ftype;

  @ffi.Int32()
  external int gpu_used;

  @ffi.Int32()
  external int gpu_fallback;
}

final class vw_job_params extends ffi.Struct {
  @ffi.Int32()
  external int struct_size;

  /// vw_job_mode
  @ffi.Int32()
  external int mode;

  /// 16 kHz, mono, PCM s16le, canonical RIFF/WAVE; validated
  external ffi.Pointer<ffi.Char> wav_path;

  /// inclusive, relative to WAV start; resume point
  @ffi.Int64()
  external int range_start_ms;

  /// exclusive; -1 = end of file
  @ffi.Int64()
  external int range_end_ms;

  /// whisper code ("en", "ja", ...); "auto" only in DETECT mode
  external ffi.Pointer<ffi.Char> language;

  /// 1..8; may change later via vw_job_set_threads
  @ffi.Int32()
  external int n_threads;

  /// 180000
  @ffi.Int32()
  external int chunk_target_ms;

  /// 15000: search +-this around the target for the quietest 400 ms
  @ffi.Int32()
  external int chunk_search_ms;

  /// 10000: a shorter tail merges into the previous chunk
  @ffi.Int32()
  external int chunk_min_ms;

  @ffi.Int32()
  external int vad_enabled;

  /// ggml-silero-v6.2.0.bin
  external ffi.Pointer<ffi.Char> vad_model_path;

  /// 0.5
  @ffi.Float()
  external double vad_threshold;

  /// 250
  @ffi.Int32()
  external int vad_min_speech_ms;

  /// 300
  @ffi.Int32()
  external int vad_min_silence_ms;

  /// 100
  @ffi.Int32()
  external int vad_speech_pad_ms;

  /// 0.1
  @ffi.Float()
  external double vad_samples_overlap_s;

  /// 1
  @ffi.Int32()
  external int token_timestamps;

  /// 0.6, 2.4, -1.0, 0.2
  @ffi.Float()
  external double no_speech_thold;

  @ffi.Float()
  external double entropy_thold;

  @ffi.Float()
  external double logprob_thold;

  @ffi.Float()
  external double temperature_inc;

  /// <= 1: greedy
  @ffi.Int32()
  external int beam_size;

  /// 5 (temperature fallback only)
  @ffi.Int32()
  external int best_of;

  /// 1 unless the user wants sound descriptions
  @ffi.Int32()
  external int suppress_nst;

  /// 0..40: tail of the previous chunk used as initial_prompt
  @ffi.Int32()
  external int carry_prompt_words;

  /// nullable; unused by the v1 UI
  external ffi.Pointer<ffi.Char> initial_prompt;

  /// DETECT: up to 30000 ms of speech after the first VAD speech start
  @ffi.Int32()
  external int detect_max_speech_ms;

  /// DETECT: search window for the first speech (600000)
  @ffi.Int32()
  external int detect_search_ms;
}

final class vw_job_status extends ffi.Struct {
  @ffi.Int32()
  external int struct_size;

  /// vw_job_state
  @ffi.Int32()
  external int state;

  /// vw_status (valid when FAILED/CANCELLED)
  @ffi.Int32()
  external int error;

  /// vw_phase
  @ffi.Int32()
  external int phase;

  /// 0..1000 over [range_start, range_end)
  @ffi.Int32()
  external int progress_permille;

  /// 0-based current chunk; count known after planning
  @ffi.Int32()
  external int chunk_index;

  @ffi.Int32()
  external int chunk_count;

  /// chunks whose segments are final
  @ffi.Int32()
  external int chunks_completed;

  /// segments available to take
  @ffi.Int32()
  external int segments_ready;

  /// audio covered by completed work
  @ffi.Int64()
  external int processed_ms;

  /// wall time spent in whisper calls (excludes pauses)
  @ffi.Int64()
  external int compute_ms;

  /// current n_threads
  @ffi.Int32()
  external int threads;

  /// language used/detected
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> language;

  @ffi.Float()
  external double language_p;
}

const int VW_ABI_VERSION = 1;
