name: vwish_ui_kit
description: Custom OLED theme, interactive canvas seek bar, and volume booster UI components.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  vwish_domain:
    path: ../vwish_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
