// OWNER: ENG-05
//
// Frame barcode reader for the ENG-05 test media (frame_counter_*.mp4 and friends), used by
// integration tests on the RGBA buffer of `PreviewSession.debugCaptureFrame` and by tests on
// frames extracted from exports. Pure Dart (dart:typed_data only): no Flutter, no I/O.
//
// Normative layout, generated by tool/make_fixtures.swift and mirrored by FrameBarcode.swift
// and FrameBarcode.kt (golden vectors in test_fixtures/media/README.md):
//
//   band     top 10 % of the frame height (at least 8 px), full width, 28 equal cells
//   cell 0   white, cell 1 black                       calibration (also fixes the threshold)
//   2..17    frame index, 16 bits, MSB first (white = 1)
//   18..25   CRC-8 (poly 0x07, init 0) of the two index bytes, MSB first
//   cell 26  white, cell 27 black                      end guard
//
// The reader samples the central 50 % x 50 % of every cell, so it tolerates compression noise,
// scaling and moderate brightness/contrast changes. A cell that is neither clearly white nor
// clearly black (a cross dissolve of two different frames) makes the whole frame `blended`
// instead of returning a wrong index.

library;

import 'dart:math' as math;
import 'dart:typed_data';

/// Byte order of the pixel buffer handed to [FrameBarcode.read].
enum FramePixelOrder {
  /// R, G, B, A (Flutter `ImageByteFormat.rawRgba`, `debugCaptureFrame`).
  rgba,

  /// B, G, R, A (Core Video / `kCVPixelFormatType_32BGRA`).
  bgra,
}

/// Why a frame did (not) decode.
enum FrameBarcodeStatus {
  /// A valid index was decoded.
  ok,

  /// No barcode contrast at all (black, white or flat frame, or no frame yet).
  noSignal,

  /// At least one cell is between black and white: two frames mixed (dissolve) or a fade.
  blended,

  /// Contrast is fine but the guard cells are wrong (inverted, cropped, rotated, letterboxed).
  badGuard,

  /// Guards are fine but the CRC does not match.
  badChecksum,
}

/// Pixel rectangle inside the buffer that holds the full source frame (for example the video
/// area of a letterboxed preview capture).
class FrameBarcodeRegion {
  /// Creates a region.
  const FrameBarcodeRegion(this.x, this.y, this.width, this.height);

  /// Left edge in pixels.
  final int x;

  /// Top edge in pixels.
  final int y;

  /// Width in pixels.
  final int width;

  /// Height in pixels.
  final int height;

  @override
  String toString() => 'FrameBarcodeRegion($x, $y, $width x $height)';
}

/// Result of [FrameBarcode.read].
class FrameBarcodeReading {
  /// Creates a reading.
  const FrameBarcodeReading(this.status, [this.index]);

  /// Outcome.
  final FrameBarcodeStatus status;

  /// Decoded frame index when [status] is [FrameBarcodeStatus.ok].
  final int? index;

  /// True when [index] is a valid decode.
  bool get isReadable => status == FrameBarcodeStatus.ok;

  @override
  String toString() => 'FrameBarcodeReading($status${index == null ? '' : ', $index'})';

  @override
  bool operator ==(Object other) =>
      other is FrameBarcodeReading && other.status == status && other.index == index;

  @override
  int get hashCode => Object.hash(status, index);
}

/// Barcode layout constants, encoder helpers (for synthetic test frames) and the reader.
abstract final class FrameBarcode {
  /// Number of cells in the band.
  static const int cellCount = 28;

  /// Band height as a fraction of the frame height.
  static const double bandFraction = 0.10;

  /// Smallest band height in pixels.
  static const int minBandHeight = 8;

  /// Largest encodable frame index.
  static const int maxIndex = 0xFFFF;

  /// A cell must be at least this fraction of the calibrated contrast away from the midpoint.
  static const double margin = 0.25;

  /// Minimum white-black luma distance (0..255) for a signal to count as a barcode.
  static const int minContrast = 48;

  /// CRC-8 (poly 0x07, init 0, no reflection) of [index] as two big-endian bytes.
  static int crc8(int index) {
    var crc = 0;
    for (final byte in <int>[(index >> 8) & 0xFF, index & 0xFF]) {
      crc ^= byte;
      for (var i = 0; i < 8; i++) {
        crc = (crc & 0x80) != 0 ? ((crc << 1) ^ 0x07) & 0xFF : (crc << 1) & 0xFF;
      }
    }
    return crc;
  }

  /// The 28 cell values (true = white) for [index].
  static List<bool> cellsFor(int index) {
    if (index < 0 || index > maxIndex) {
      throw RangeError.range(index, 0, maxIndex, 'index');
    }
    final cells = <bool>[true, false];
    for (var b = 15; b >= 0; b--) {
      cells.add(((index >> b) & 1) == 1);
    }
    final crc = crc8(index);
    for (var b = 7; b >= 0; b--) {
      cells.add(((crc >> b) & 1) == 1);
    }
    cells
      ..add(true)
      ..add(false);
    return cells;
  }

  /// Height of the band for a frame (or region) [frameHeight] pixels tall.
  static int bandHeight(int frameHeight) {
    final h = (frameHeight * bandFraction).round();
    final clamped = h < minBandHeight ? minBandHeight : h;
    return clamped > frameHeight ? frameHeight : clamped;
  }

  /// Decodes the frame index, or null when the frame is not a clean barcode frame.
  static int? decode(
    Uint8List pixels, {
    required int width,
    required int height,
    int? bytesPerRow,
    FramePixelOrder order = FramePixelOrder.rgba,
    FrameBarcodeRegion? region,
  }) =>
      read(pixels,
              width: width, height: height, bytesPerRow: bytesPerRow, order: order, region: region)
          .index;

  /// Reads the barcode and reports why it failed when it does.
  static FrameBarcodeReading read(
    Uint8List pixels, {
    required int width,
    required int height,
    int? bytesPerRow,
    FramePixelOrder order = FramePixelOrder.rgba,
    FrameBarcodeRegion? region,
  }) {
    final stride = bytesPerRow ?? width * 4;
    final rx = region?.x ?? 0;
    final ry = region?.y ?? 0;
    final rw = region?.width ?? width;
    final rh = region?.height ?? height;
    if (rw < cellCount || rh < 1 || rx < 0 || ry < 0 || rx + rw > width || ry + rh > height) {
      throw ArgumentError('region $region does not fit a ${width}x$height frame');
    }
    if (pixels.length < stride * (height - 1) + width * 4) {
      throw ArgumentError('pixel buffer too small for ${width}x$height stride $stride');
    }
    final rIdx = order == FramePixelOrder.rgba ? 0 : 2;
    final bIdx = order == FramePixelOrder.rgba ? 2 : 0;

    final bandH = bandHeight(rh);
    final y0 = ry + bandH ~/ 4;
    final y1 = math.max(ry + (bandH * 3) ~/ 4, y0 + 1);

    final luma = List<int>.filled(cellCount, 0);
    for (var i = 0; i < cellCount; i++) {
      final cx0 = rx + i * rw ~/ cellCount;
      final cx1 = rx + (i + 1) * rw ~/ cellCount;
      final cw = cx1 - cx0;
      var sx0 = cx0 + cw ~/ 4;
      var sx1 = cx1 - cw ~/ 4;
      if (sx1 <= sx0) {
        sx0 = cx0;
        sx1 = cx1;
      }
      var sum = 0;
      var n = 0;
      for (var y = y0; y < y1; y++) {
        var p = y * stride + sx0 * 4;
        for (var x = sx0; x < sx1; x++, p += 4) {
          // BT.709-ish integer luma.
          sum += 54 * pixels[p + rIdx] + 183 * pixels[p + 1] + 19 * pixels[p + bIdx];
          n++;
        }
      }
      luma[i] = n == 0 ? 0 : sum ~/ (256 * n);
    }

    final white = luma[0];
    final black = luma[1];
    final contrast = white - black;
    if (contrast <= -minContrast) {
      // Calibration cells swapped: an inverted frame.
      return const FrameBarcodeReading(FrameBarcodeStatus.badGuard);
    }
    if (contrast < minContrast) {
      return const FrameBarcodeReading(FrameBarcodeStatus.noSignal);
    }
    final mid = (white + black) / 2;
    final guard = contrast * margin;
    final bits = List<bool>.filled(cellCount, false);
    for (var i = 0; i < cellCount; i++) {
      final v = luma[i];
      if (v > mid + guard) {
        bits[i] = true;
      } else if (v < mid - guard) {
        bits[i] = false;
      } else {
        return const FrameBarcodeReading(FrameBarcodeStatus.blended);
      }
    }
    if (!bits[0] || bits[1] || !bits[26] || bits[27]) {
      return const FrameBarcodeReading(FrameBarcodeStatus.badGuard);
    }
    var index = 0;
    for (var i = 2; i < 18; i++) {
      index = (index << 1) | (bits[i] ? 1 : 0);
    }
    var crc = 0;
    for (var i = 18; i < 26; i++) {
      crc = (crc << 1) | (bits[i] ? 1 : 0);
    }
    if (crc != crc8(index)) {
      return const FrameBarcodeReading(FrameBarcodeStatus.badChecksum);
    }
    return FrameBarcodeReading(FrameBarcodeStatus.ok, index);
  }

  /// Paints the barcode band for [index] into [pixels] (opaque, the rest of the buffer is left
  /// untouched). Synthetic frames for unit tests and for tools that need a known-good frame.
  static void paint(
    Uint8List pixels, {
    required int width,
    required int height,
    required int index,
    int? bytesPerRow,
    FrameBarcodeRegion? region,
    int white = 255,
    int black = 0,
  }) {
    final stride = bytesPerRow ?? width * 4;
    final rx = region?.x ?? 0;
    final ry = region?.y ?? 0;
    final rw = region?.width ?? width;
    final rh = region?.height ?? height;
    final cells = cellsFor(index);
    final bandH = bandHeight(rh);
    for (var i = 0; i < cellCount; i++) {
      final x0 = rx + i * rw ~/ cellCount;
      final x1 = rx + (i + 1) * rw ~/ cellCount;
      final v = cells[i] ? white : black;
      for (var y = ry; y < ry + bandH; y++) {
        var p = y * stride + x0 * 4;
        for (var x = x0; x < x1; x++, p += 4) {
          pixels[p] = v;
          pixels[p + 1] = v;
          pixels[p + 2] = v;
          pixels[p + 3] = 255;
        }
      }
    }
  }
}
