// AND-01 spike host app. Throwaway (ARCH D-42): instrumented tests under src/androidTest answer
// V-N1..V-N6, V-N15..V-N19, V-N23..V-N25 on the emulator. The dependency block and the lint
// opt-in configuration are what ENG-06 copies into packages/vwish_editor_engine/android.

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

val media3Version = "1.11.1"

android {
    namespace = "com.vecvel.vwish.spike.engine"
    compileSdk = 36
    // Installed with the SDK (no download); used only by the contingency prototype's JNI shim.
    ndkVersion = "28.2.13676358"

    defaultConfig {
        applicationId = "com.vecvel.vwish.spike.engine"
        // The editor gate is API 29 + GLES 3 + 2 GB (ARCH §3.2); the spike runs at the same floor.
        minSdk = 29
        targetSdk = 36
        versionCode = 1
        versionName = "0.1-spike"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        ndk { abiFilters += listOf("arm64-v8a") }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        getByName("main") { java.srcDirs("src/main/kotlin") }
        getByName("test") { java.srcDirs("src/test/kotlin") }
        getByName("androidTest") {
            java.srcDirs("src/androidTest/kotlin")
            // Media generated by tool/gen_media.sh (git-ignored) and the shared frame-grid vectors.
            assets.srcDirs("../media", "../../../packages/vwish_editor_core/test/fixtures/vectors")
        }
    }

    androidResources {
        noCompress += listOf("mp4", "mov", "png", "wav", "json")
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    lint {
        // ARCH §3.2: every Media3 call site must opt in explicitly. ENG-08/ENG-06 mirror this.
        lintConfig = file("lint.xml")
        abortOnError = true
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
        optIn.add("kotlin.RequiresOptIn")
    }
}

dependencies {
    implementation("androidx.media3:media3-common:$media3Version")
    implementation("androidx.media3:media3-exoplayer:$media3Version")
    implementation("androidx.media3:media3-effect:$media3Version")
    implementation("androidx.media3:media3-transformer:$media3Version")
    implementation("androidx.media3:media3-muxer:$media3Version")
    implementation("androidx.media3:media3-inspector:$media3Version")
    implementation("androidx.media3:media3-inspector-frame:$media3Version")

    testImplementation("junit:junit:4.13.2")
    testImplementation("org.json:json:20240303")

    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test:rules:1.6.1")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("junit:junit:4.13.2")
}
