name: vwish_engine
description: PlaybackEngine abstraction and libmpv/media_kit binding implementations.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  vwish_domain:
    path: ../vwish_domain
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
