@file:OptIn(UnstableApi::class, ExperimentalApi::class)

package com.vecvel.vwish.spike.engine

import android.content.Context
import android.net.Uri
import android.util.Log
import androidx.media3.common.util.ExperimentalApi
import androidx.media3.common.util.UnstableApi
import androidx.media3.inspector.MediaExtractorCompat
import androidx.test.platform.app.InstrumentationRegistry
import java.io.File
import java.util.concurrent.ConcurrentHashMap
import org.json.JSONArray
import org.json.JSONObject

/** Media generated by tool/gen_media.sh, packaged as androidTest assets and copied to the cache. */
object TestMedia {
    val target: Context get() = InstrumentationRegistry.getInstrumentation().targetContext
    private val sampleCache = ConcurrentHashMap<String, LongArray>()

    /** Export outputs (filesDir: the emulator's /data is nearly full and the system clears cacheDir). */
    val outDir: File get() = File(target.filesDir, "out").apply { mkdirs() }

    fun file(name: String): File {
        val dir = File(target.filesDir, "media").apply { mkdirs() }
        val f = File(dir, name)
        if (!f.exists() || f.length() == 0L) {
            InstrumentationRegistry.getInstrumentation().context.assets.open(name).use { input ->
                f.outputStream().use { input.copyTo(it) }
            }
        }
        return f
    }

    fun uri(name: String): String = Uri.fromFile(file(name)).toString()

    /** Presentation times (µs, sorted) of the first video track as Media3's extractor reports them. */
    fun videoSampleTimesUs(name: String): LongArray = sampleCache.getOrPut(name) { sampleTimes(file(name), "video/") }

    fun sampleTimes(f: File, mimePrefix: String): LongArray {
        val ex = MediaExtractorCompat(target)
        try {
            ex.setDataSource(Uri.fromFile(f), 0)
            val track = (0 until ex.trackCount).first {
                ex.getTrackFormat(it).getString(android.media.MediaFormat.KEY_MIME)!!.startsWith(mimePrefix)
            }
            ex.selectTrack(track)
            val out = ArrayList<Long>()
            while (true) {
                val t = ex.sampleTime
                if (t < 0) break
                out += t
                if (!ex.advance()) break
            }
            return out.sorted().toLongArray()
        } finally {
            ex.release()
        }
    }

    /** Index of the sample with the greatest PTS ≤ s + 500 µs (ARCH §11.5 source-frame rule). */
    fun ruleFrame(times: LongArray, sUs: Long): Int {
        var lo = 0
        var hi = times.size - 1
        var ans = 0
        while (lo <= hi) {
            val mid = (lo + hi) ushr 1
            if (times[mid] <= sUs + 500) {
                ans = mid
                lo = mid + 1
            } else {
                hi = mid - 1
            }
        }
        return ans
    }
}

/** Results pulled by tool/run_spike.sh and summarized in docs/editor/spikes/AND-01.md. */
object Results {
    fun write(name: String, json: JSONObject) {
        val dir = File(TestMedia.target.getExternalFilesDir(null), "results").apply { mkdirs() }
        File(dir, "$name.json").writeText(json.toString(2))
        Log.i("AND01", "$name: $json")
    }

    fun arr(values: Iterable<Any?>) = JSONArray().apply { values.forEach { put(it) } }

    fun stats(values: List<Double>): JSONObject {
        if (values.isEmpty()) return JSONObject().put("n", 0)
        val s = values.sorted()
        fun q(p: Double) = s[((s.size - 1) * p).toInt()]
        return JSONObject()
            .put("n", s.size)
            .put("min", s.first())
            .put("p50", q(0.5))
            .put("p90", q(0.9))
            .put("max", s.last())
            .put("mean", s.average())
    }
}
