// OWNER: CORE-03
//
// Subtitle tracks, styles and AI caption provenance (ARCH §6.6; ai.md §10.2 adopted verbatim,
// schema 1). Cues themselves are `SubtitleCue` items (items.dart).

import 'package:collection/collection.dart';
import 'package:meta/meta.dart';

import '../ids/ids.dart';
import '../time/time.dart';
import 'text_style.dart';

const Object _keep = Object();

/// Where a cue came from.
enum CueOrigin {
  /// Typed in the editor.
  manual,

  /// Imported from SRT/VTT.
  imported,

  /// Generated by Auto captions.
  generated,
}

/// Visual style shared by every cue of a subtitle track.
@immutable
final class SubtitleStyle {
  /// Creates a style; the default is Figtree 42 pt white with a translucent box.
  const SubtitleStyle({
    this.fontFamily = 'figtree',
    this.fontSizePt = 42,
    this.bold = false,
    this.italic = false,
    this.color = 0xFFFFFFFF,
    this.background = const BoxStyle(),
    this.outline,
    this.shadow,
    this.maxLines = 2,
    this.maxWidth = 0.9,
    this.align = TextAlignH.center,
  });

  /// Content-font id (D-30).
  final String fontFamily;

  /// Size in points at a 1,080 px short side.
  final double fontSizePt;

  /// Bold.
  final bool bold;

  /// Italic.
  final bool italic;

  /// ARGB text colour.
  final int color;

  /// Optional box behind each cue.
  final BoxStyle? background;

  /// Optional outline.
  final StrokeStyle? outline;

  /// Optional shadow.
  final ShadowStyle? shadow;

  /// Maximum lines per cue, 1..3.
  final int maxLines;

  /// Wrap width as a fraction of the canvas width.
  final double maxWidth;

  /// Line alignment.
  final TextAlignH align;

  /// A copy with the given fields replaced; pass null to remove background/outline/shadow.
  SubtitleStyle copyWith({
    String? fontFamily,
    double? fontSizePt,
    bool? bold,
    bool? italic,
    int? color,
    Object? background = _keep,
    Object? outline = _keep,
    Object? shadow = _keep,
    int? maxLines,
    double? maxWidth,
    TextAlignH? align,
  }) =>
      SubtitleStyle(
        fontFamily: fontFamily ?? this.fontFamily,
        fontSizePt: fontSizePt ?? this.fontSizePt,
        bold: bold ?? this.bold,
        italic: italic ?? this.italic,
        color: color ?? this.color,
        background: identical(background, _keep) ? this.background : background as BoxStyle?,
        outline: identical(outline, _keep) ? this.outline : outline as StrokeStyle?,
        shadow: identical(shadow, _keep) ? this.shadow : shadow as ShadowStyle?,
        maxLines: maxLines ?? this.maxLines,
        maxWidth: maxWidth ?? this.maxWidth,
        align: align ?? this.align,
      );

  @override
  bool operator ==(Object other) =>
      other is SubtitleStyle &&
      other.fontFamily == fontFamily &&
      other.fontSizePt == fontSizePt &&
      other.bold == bold &&
      other.italic == italic &&
      other.color == color &&
      other.background == background &&
      other.outline == outline &&
      other.shadow == shadow &&
      other.maxLines == maxLines &&
      other.maxWidth == maxWidth &&
      other.align == align;

  @override
  int get hashCode => Object.hash(
      fontFamily, fontSizePt, bold, italic, color, background, outline, shadow, maxLines, maxWidth, align);
}

/// Vertical placement of a subtitle track's cues. Safe margin default 0.06 of the canvas height.
@immutable
sealed class SubtitlePosition {
  const SubtitlePosition();

  /// Bottom, inside the safe margin (default).
  static const SubtitlePosition bottom = BottomSubtitlePosition();

  /// Top, inside the safe margin.
  static const SubtitlePosition top = TopSubtitlePosition();
}

/// Bottom placement.
final class BottomSubtitlePosition extends SubtitlePosition {
  /// Creates the bottom placement.
  const BottomSubtitlePosition();

  @override
  bool operator ==(Object other) => other is BottomSubtitlePosition;

  @override
  int get hashCode => 1;
}

/// Top placement.
final class TopSubtitlePosition extends SubtitlePosition {
  /// Creates the top placement.
  const TopSubtitlePosition();

  @override
  bool operator ==(Object other) => other is TopSubtitlePosition;

  @override
  int get hashCode => 2;
}

/// Custom placement: the cue block's vertical centre at [yFraction] of the canvas height.
final class CustomSubtitlePosition extends SubtitlePosition {
  /// Creates a custom placement.
  const CustomSubtitlePosition(this.yFraction);

  /// 0 = top edge, 1 = bottom edge.
  final double yFraction;

  @override
  bool operator ==(Object other) => other is CustomSubtitlePosition && other.yFraction == yFraction;

  @override
  int get hashCode => yFraction.hashCode;
}

/// Caption segmentation presets (ai.md §9.2).
enum SegmentationPreset {
  /// 2 lines × 42 graphemes (32 for 9:16).
  standard,

  /// One line per cue.
  singleLine,

  /// Short phrases.
  shortPhrases,
}

/// Segmentation parameters recorded with generated captions so "Regenerate → re-split" is
/// reproducible. Stored in the project (schema 1).
@immutable
final class SegmentationSettings {
  /// Creates settings; zero values mean "preset default for the script and aspect".
  const SegmentationSettings({
    this.preset = SegmentationPreset.standard,
    this.maxLines = 0,
    this.maxCharsPerLine = 0,
    this.maxCharsPerSecond = 0,
  });

  /// Preset.
  final SegmentationPreset preset;

  /// Override of the preset's line count (0 = default).
  final int maxLines;

  /// Override of graphemes per line (0 = default).
  final int maxCharsPerLine;

  /// Override of reading speed in graphemes per second (0 = default).
  final double maxCharsPerSecond;

  @override
  bool operator ==(Object other) =>
      other is SegmentationSettings &&
      other.preset == preset &&
      other.maxLines == maxLines &&
      other.maxCharsPerLine == maxCharsPerLine &&
      other.maxCharsPerSecond == maxCharsPerSecond;

  @override
  int get hashCode => Object.hash(preset, maxLines, maxCharsPerLine, maxCharsPerSecond);
}

/// What an Auto captions run transcribed (clip ids, track ids, optional timeline range).
@immutable
final class CaptionScopeData {
  /// Creates scope data.
  CaptionScopeData({List<ItemId> clips = const [], List<TrackId> tracks = const [], this.range})
      : clips = List.unmodifiable(clips),
        tracks = List.unmodifiable(tracks);

  /// Selected clips (empty = not clip-scoped).
  final List<ItemId> clips;

  /// Tracks included (empty = all eligible).
  final List<TrackId> tracks;

  /// Timeline range, or null for the whole timeline.
  final TimeRange? range;

  @override
  bool operator ==(Object other) =>
      other is CaptionScopeData &&
      const ListEquality<ItemId>().equals(other.clips, clips) &&
      const ListEquality<TrackId>().equals(other.tracks, tracks) &&
      other.range == range;

  @override
  int get hashCode => Object.hash(Object.hashAll(clips), Object.hashAll(tracks), range);
}

/// Provenance of a generated caption track (ai.md §10.2, adopted verbatim; schema 1).
@immutable
final class CaptionProvenance {
  /// Creates provenance.
  CaptionProvenance({
    required this.generator,
    required this.engineVersion,
    required this.modelId,
    required this.modelSha256,
    required this.language,
    required this.languageDetected,
    this.languageConfidence,
    required this.segmentation,
    required this.scope,
    List<String> transcriptKeys = const [],
    required this.generatedAt,
    this.schema = 1,
  }) : transcriptKeys = List.unmodifiable(transcriptKeys);

  /// `whisper.cpp`.
  final String generator;

  /// Engine version, e.g. `1.9.4`.
  final String engineVersion;

  /// Catalog model id, e.g. `whisper-base-q5_1`.
  final String modelId;

  /// SHA-256 of the model file.
  final String modelSha256;

  /// BCP-47 language of the captions.
  final String language;

  /// Whether the language was detected rather than chosen.
  final bool languageDetected;

  /// Detection confidence when detected.
  final double? languageConfidence;

  /// Segmentation used.
  final SegmentationSettings segmentation;

  /// What was transcribed.
  final CaptionScopeData scope;

  /// Transcript cache keys for instant re-split.
  final List<String> transcriptKeys;

  /// When the captions were generated (UTC).
  final DateTime generatedAt;

  /// Provenance schema (1).
  final int schema;

  @override
  bool operator ==(Object other) =>
      other is CaptionProvenance &&
      other.generator == generator &&
      other.engineVersion == engineVersion &&
      other.modelId == modelId &&
      other.modelSha256 == modelSha256 &&
      other.language == language &&
      other.languageDetected == languageDetected &&
      other.languageConfidence == languageConfidence &&
      other.segmentation == segmentation &&
      other.scope == scope &&
      const ListEquality<String>().equals(other.transcriptKeys, transcriptKeys) &&
      other.generatedAt == generatedAt &&
      other.schema == schema;

  @override
  int get hashCode => Object.hash(generator, engineVersion, modelId, modelSha256, language, languageDetected,
      languageConfidence, segmentation, scope, Object.hashAll(transcriptKeys), generatedAt, schema);
}

/// Per-track subtitle data, present exactly on subtitle tracks (ARCH §6.6, invariant I8).
@immutable
final class SubtitleTrackData {
  /// Creates subtitle track data.
  const SubtitleTrackData({
    this.language,
    this.style = const SubtitleStyle(),
    this.position = SubtitlePosition.bottom,
    this.burnIn = true,
    this.provenance,
  });

  /// BCP-47 language tag, if known.
  final String? language;

  /// Cue style.
  final SubtitleStyle style;

  /// Vertical placement.
  final SubtitlePosition position;

  /// Default of the export sheet's per-track "Burn into video" switch.
  final bool burnIn;

  /// Present when the track was generated by Auto captions.
  final CaptionProvenance? provenance;

  /// A copy with the given fields replaced; pass null to clear language/provenance.
  SubtitleTrackData copyWith({
    Object? language = _keep,
    SubtitleStyle? style,
    SubtitlePosition? position,
    bool? burnIn,
    Object? provenance = _keep,
  }) =>
      SubtitleTrackData(
        language: identical(language, _keep) ? this.language : language as String?,
        style: style ?? this.style,
        position: position ?? this.position,
        burnIn: burnIn ?? this.burnIn,
        provenance: identical(provenance, _keep) ? this.provenance : provenance as CaptionProvenance?,
      );

  @override
  bool operator ==(Object other) =>
      other is SubtitleTrackData &&
      other.language == language &&
      other.style == style &&
      other.position == position &&
      other.burnIn == burnIn &&
      other.provenance == provenance;

  @override
  int get hashCode => Object.hash(language, style, position, burnIn, provenance);
}

/// A cue proposed by Auto captions before it is inserted: timeline range (frame-quantized) and
/// text with `\n` between lines.
@immutable
final class SubtitleCueDraft {
  /// Creates a draft.
  const SubtitleCueDraft(this.range, this.text);

  /// Timeline range on the project grid.
  final TimeRange range;

  /// Cue text.
  final String text;

  @override
  bool operator ==(Object other) => other is SubtitleCueDraft && other.range == range && other.text == text;

  @override
  int get hashCode => Object.hash(range, text);
}
