// OWNER: ENG-05
//
// Swift frame barcode reader for native tests (XCTest in RunnerTests, the iOS spike hosts and
// anything that can hand over pixels). Mirror of lib/src/testing/frame_barcode.dart and
// FrameBarcode.kt; the layout is generated by tool/make_fixtures.swift:
//
//   band     top 10 % of the frame height (at least 8 px), full width, 28 equal cells
//   cell 0   white, cell 1 black                       calibration (also fixes the threshold)
//   2..17    frame index, 16 bits, MSB first (white = 1)
//   18..25   CRC-8 (poly 0x07, init 0) of the two index bytes, MSB first
//   cell 26  white, cell 27 black                      end guard
//
// Foundation, CoreGraphics and CoreVideo only (no XCTest) so it also compiles in a plain
// command line harness. Golden vectors: test_fixtures/media/README.md.

import CoreGraphics
import CoreVideo
import Foundation

enum FrameBarcodeStatus: Equatable {
    case ok, noSignal, blended, badGuard, badChecksum
}

struct FrameBarcodeReading: Equatable {
    let status: FrameBarcodeStatus
    let index: Int?
    var isReadable: Bool { status == .ok }
}

enum FramePixelOrder { case rgba, bgra }

/// Pixel rectangle that holds the full source frame inside a larger buffer.
struct FrameBarcodeRegion: Equatable {
    let x: Int, y: Int, width: Int, height: Int
}

enum FrameBarcode {
    static let cellCount = 28
    static let bandFraction = 0.10
    static let minBandHeight = 8
    static let maxIndex = 0xFFFF
    /// A cell must be at least this fraction of the calibrated contrast away from the midpoint.
    static let margin = 0.25
    static let minContrast = 48

    static func crc8(_ index: Int) -> Int {
        var crc = 0
        for byte in [(index >> 8) & 0xFF, index & 0xFF] {
            crc ^= byte
            for _ in 0..<8 {
                crc = (crc & 0x80) != 0 ? ((crc << 1) ^ 0x07) & 0xFF : (crc << 1) & 0xFF
            }
        }
        return crc
    }

    static func cells(for index: Int) -> [Bool] {
        precondition(index >= 0 && index <= maxIndex, "barcode index out of range")
        var bits: [Bool] = [true, false]
        for b in stride(from: 15, through: 0, by: -1) { bits.append(((index >> b) & 1) == 1) }
        let crc = crc8(index)
        for b in stride(from: 7, through: 0, by: -1) { bits.append(((crc >> b) & 1) == 1) }
        bits.append(true)
        bits.append(false)
        return bits
    }

    static func bandHeight(frameHeight: Int) -> Int {
        let h = max(Int((Double(frameHeight) * bandFraction).rounded()), minBandHeight)
        return min(h, frameHeight)
    }

    // MARK: Entry points

    /// Reads interleaved 4-byte pixels.
    static func read(
        pixels: UnsafeRawBufferPointer, width: Int, height: Int, bytesPerRow: Int? = nil,
        order: FramePixelOrder = .rgba, region: FrameBarcodeRegion? = nil
    ) -> FrameBarcodeReading {
        let stride = bytesPerRow ?? width * 4
        let r = region ?? FrameBarcodeRegion(x: 0, y: 0, width: width, height: height)
        precondition(r.width >= cellCount && r.x >= 0 && r.y >= 0 && r.x + r.width <= width
                     && r.y + r.height <= height, "region does not fit the frame")
        precondition(pixels.count >= stride * (height - 1) + width * 4, "pixel buffer too small")
        let rIdx = order == .rgba ? 0 : 2
        let bIdx = order == .rgba ? 2 : 0
        return decodeCells(region: r) { x0, x1, y0, y1 in
            var sum = 0, n = 0
            for y in y0..<y1 {
                var p = y * stride + x0 * 4
                for _ in x0..<x1 {
                    sum += 54 * Int(pixels[p + rIdx]) + 183 * Int(pixels[p + 1]) + 19 * Int(pixels[p + bIdx])
                    n += 1
                    p += 4
                }
            }
            return n == 0 ? 0 : sum / (256 * n)
        }
    }

    static func read(
        pixels: [UInt8], width: Int, height: Int, bytesPerRow: Int? = nil,
        order: FramePixelOrder = .rgba, region: FrameBarcodeRegion? = nil
    ) -> FrameBarcodeReading {
        pixels.withUnsafeBytes {
            read(pixels: $0, width: width, height: height, bytesPerRow: bytesPerRow, order: order, region: region)
        }
    }

    static func decode(
        pixels: [UInt8], width: Int, height: Int, bytesPerRow: Int? = nil,
        order: FramePixelOrder = .rgba, region: FrameBarcodeRegion? = nil
    ) -> Int? {
        read(pixels: pixels, width: width, height: height, bytesPerRow: bytesPerRow, order: order, region: region).index
    }

    /// Reads a CGImage (any pixel format; drawn into BGRA first).
    static func read(cgImage: CGImage, region: FrameBarcodeRegion? = nil) -> FrameBarcodeReading {
        let w = cgImage.width, h = cgImage.height
        var buf = [UInt8](repeating: 0, count: w * h * 4)
        let cs = CGColorSpace(name: CGColorSpace.sRGB)!
        let ok: Bool = buf.withUnsafeMutableBytes { raw in
            guard let ctx = CGContext(
                data: raw.baseAddress, width: w, height: h, bitsPerComponent: 8, bytesPerRow: w * 4, space: cs,
                bitmapInfo: CGImageAlphaInfo.premultipliedFirst.rawValue | CGBitmapInfo.byteOrder32Little.rawValue)
            else { return false }
            ctx.draw(cgImage, in: CGRect(x: 0, y: 0, width: w, height: h))
            return true
        }
        guard ok else { return FrameBarcodeReading(status: .noSignal, index: nil) }
        return read(pixels: buf, width: w, height: h, order: .bgra, region: region)
    }

    /// Reads a CVPixelBuffer: 32BGRA/32RGBA directly, 8- and 10-bit bi-planar 4:2:0 from the luma plane.
    static func read(pixelBuffer: CVPixelBuffer, region: FrameBarcodeRegion? = nil) -> FrameBarcodeReading {
        CVPixelBufferLockBaseAddress(pixelBuffer, .readOnly)
        defer { CVPixelBufferUnlockBaseAddress(pixelBuffer, .readOnly) }
        let format = CVPixelBufferGetPixelFormatType(pixelBuffer)
        let w = CVPixelBufferGetWidth(pixelBuffer), h = CVPixelBufferGetHeight(pixelBuffer)
        switch format {
        case kCVPixelFormatType_32BGRA, kCVPixelFormatType_32RGBA:
            let bpr = CVPixelBufferGetBytesPerRow(pixelBuffer)
            let raw = UnsafeRawBufferPointer(start: CVPixelBufferGetBaseAddress(pixelBuffer), count: bpr * h)
            return read(pixels: raw, width: w, height: h, bytesPerRow: bpr,
                        order: format == kCVPixelFormatType_32BGRA ? .bgra : .rgba, region: region)
        case kCVPixelFormatType_420YpCbCr8BiPlanarFullRange, kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange:
            let bpr = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, 0)
            let base = CVPixelBufferGetBaseAddressOfPlane(pixelBuffer, 0)!.assumingMemoryBound(to: UInt8.self)
            let r = region ?? FrameBarcodeRegion(x: 0, y: 0, width: w, height: h)
            return decodeCells(region: r) { x0, x1, y0, y1 in
                var sum = 0, n = 0
                for y in y0..<y1 { for x in x0..<x1 { sum += Int(base[y * bpr + x]); n += 1 } }
                return n == 0 ? 0 : sum / n
            }
        case kCVPixelFormatType_420YpCbCr10BiPlanarFullRange, kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange:
            let bpr = CVPixelBufferGetBytesPerRowOfPlane(pixelBuffer, 0)
            let base = CVPixelBufferGetBaseAddressOfPlane(pixelBuffer, 0)!
            let r = region ?? FrameBarcodeRegion(x: 0, y: 0, width: w, height: h)
            return decodeCells(region: r) { x0, x1, y0, y1 in
                var sum = 0, n = 0
                for y in y0..<y1 {
                    let row = base.advanced(by: y * bpr).assumingMemoryBound(to: UInt16.self)
                    for x in x0..<x1 { sum += Int(row[x] >> 8); n += 1 }   // 10-bit in the high bits
                }
                return n == 0 ? 0 : sum / n
            }
        default:
            return FrameBarcodeReading(status: .noSignal, index: nil)
        }
    }

    // MARK: Core

    /// `meanLuma(x0, x1, y0, y1)` returns the mean 0...255 luma of the pixel box.
    private static func decodeCells(
        region r: FrameBarcodeRegion, meanLuma: (Int, Int, Int, Int) -> Int
    ) -> FrameBarcodeReading {
        let bandH = bandHeight(frameHeight: r.height)
        let y0 = r.y + bandH / 4
        let y1 = max(r.y + (bandH * 3) / 4, y0 + 1)
        var luma = [Int](repeating: 0, count: cellCount)
        for i in 0..<cellCount {
            let cx0 = r.x + i * r.width / cellCount
            let cx1 = r.x + (i + 1) * r.width / cellCount
            let cw = cx1 - cx0
            var sx0 = cx0 + cw / 4, sx1 = cx1 - cw / 4
            if sx1 <= sx0 { sx0 = cx0; sx1 = cx1 }
            luma[i] = meanLuma(sx0, sx1, y0, y1)
        }
        let white = luma[0], black = luma[1]
        let contrast = white - black
        if contrast <= -minContrast { return FrameBarcodeReading(status: .badGuard, index: nil) }
        if contrast < minContrast { return FrameBarcodeReading(status: .noSignal, index: nil) }
        let mid = Double(white + black) / 2
        let guardBand = Double(contrast) * margin
        var bits = [Bool](repeating: false, count: cellCount)
        for i in 0..<cellCount {
            let v = Double(luma[i])
            if v > mid + guardBand { bits[i] = true }
            else if v < mid - guardBand { bits[i] = false }
            else { return FrameBarcodeReading(status: .blended, index: nil) }
        }
        if !bits[0] || bits[1] || !bits[26] || bits[27] {
            return FrameBarcodeReading(status: .badGuard, index: nil)
        }
        var index = 0
        for i in 2..<18 { index = (index << 1) | (bits[i] ? 1 : 0) }
        var crc = 0
        for i in 18..<26 { crc = (crc << 1) | (bits[i] ? 1 : 0) }
        if crc != crc8(index) { return FrameBarcodeReading(status: .badChecksum, index: nil) }
        return FrameBarcodeReading(status: .ok, index: index)
    }

    // MARK: Synthetic frames (tests of the reader itself)

    /// Paints the band for `index` into an interleaved 4-byte buffer.
    static func paint(
        into pixels: inout [UInt8], width: Int, height: Int, index: Int, bytesPerRow: Int? = nil,
        region: FrameBarcodeRegion? = nil, white: UInt8 = 255, black: UInt8 = 0
    ) {
        let stride = bytesPerRow ?? width * 4
        let r = region ?? FrameBarcodeRegion(x: 0, y: 0, width: width, height: height)
        let bits = cells(for: index)
        let bandH = bandHeight(frameHeight: r.height)
        for i in 0..<cellCount {
            let x0 = r.x + i * r.width / cellCount, x1 = r.x + (i + 1) * r.width / cellCount
            let v = bits[i] ? white : black
            for y in r.y..<(r.y + bandH) {
                var p = y * stride + x0 * 4
                for _ in x0..<x1 {
                    pixels[p] = v; pixels[p + 1] = v; pixels[p + 2] = v; pixels[p + 3] = 255
                    p += 4
                }
            }
        }
    }
}
