// OWNER: ENG-05
//
// Kotlin frame barcode reader for instrumented tests (androidTest) and JVM unit tests (the
// JVM test source set includes this directory, see BitmapFrameBarcode.kt and the fixtures
// README). Mirror of lib/src/testing/frame_barcode.dart and FrameBarcode.swift; the layout is
// generated by tool/make_fixtures.swift:
//
//   band     top 10 % of the frame height (at least 8 px), full width, 28 equal cells
//   cell 0   white, cell 1 black                       calibration (also fixes the threshold)
//   2..17    frame index, 16 bits, MSB first (white = 1)
//   18..25   CRC-8 (poly 0x07, init 0) of the two index bytes, MSB first
//   cell 26  white, cell 27 black                      end guard
//
// This file has NO Android imports so it compiles on the plain JVM.

package com.vecvel.vwish.editor.engine.support

/** Why a frame did (not) decode. */
enum class FrameBarcodeStatus { OK, NO_SIGNAL, BLENDED, BAD_GUARD, BAD_CHECKSUM }

/** Outcome of [FrameBarcode.read]. */
data class FrameBarcodeReading(val status: FrameBarcodeStatus, val index: Int? = null) {
    val isReadable: Boolean get() = status == FrameBarcodeStatus.OK
}

/** Byte order of an interleaved 4-byte pixel buffer. */
enum class FramePixelOrder { RGBA, BGRA }

/** Pixel rectangle that holds the full source frame inside a larger buffer. */
data class FrameBarcodeRegion(val x: Int, val y: Int, val width: Int, val height: Int)

object FrameBarcode {
    const val CELL_COUNT = 28
    const val BAND_FRACTION = 0.10
    const val MIN_BAND_HEIGHT = 8
    const val MAX_INDEX = 0xFFFF

    /** A cell must be at least this fraction of the calibrated contrast away from the midpoint. */
    const val MARGIN = 0.25
    const val MIN_CONTRAST = 48

    fun crc8(index: Int): Int {
        var crc = 0
        for (byte in intArrayOf((index shr 8) and 0xFF, index and 0xFF)) {
            crc = crc xor byte
            repeat(8) {
                crc = if (crc and 0x80 != 0) ((crc shl 1) xor 0x07) and 0xFF else (crc shl 1) and 0xFF
            }
        }
        return crc
    }

    fun cellsFor(index: Int): BooleanArray {
        require(index in 0..MAX_INDEX) { "barcode index out of range: $index" }
        val cells = ArrayList<Boolean>(CELL_COUNT)
        cells.add(true)
        cells.add(false)
        for (b in 15 downTo 0) cells.add(((index shr b) and 1) == 1)
        val crc = crc8(index)
        for (b in 7 downTo 0) cells.add(((crc shr b) and 1) == 1)
        cells.add(true)
        cells.add(false)
        return cells.toBooleanArray()
    }

    fun bandHeight(frameHeight: Int): Int =
        minOf(maxOf(Math.round(frameHeight * BAND_FRACTION).toInt(), MIN_BAND_HEIGHT), frameHeight)

    /** Decodes the frame index or returns null. */
    fun decode(
        pixels: ByteArray,
        width: Int,
        height: Int,
        bytesPerRow: Int = width * 4,
        order: FramePixelOrder = FramePixelOrder.RGBA,
        region: FrameBarcodeRegion? = null,
    ): Int? = read(pixels, width, height, bytesPerRow, order, region).index

    /** Reads interleaved 4-byte pixels (for example `ImageReader` or PNG decoded RGBA). */
    fun read(
        pixels: ByteArray,
        width: Int,
        height: Int,
        bytesPerRow: Int = width * 4,
        order: FramePixelOrder = FramePixelOrder.RGBA,
        region: FrameBarcodeRegion? = null,
    ): FrameBarcodeReading {
        require(pixels.size >= bytesPerRow * (height - 1) + width * 4) { "pixel buffer too small" }
        val rIdx = if (order == FramePixelOrder.RGBA) 0 else 2
        val bIdx = if (order == FramePixelOrder.RGBA) 2 else 0
        val r = checkedRegion(region, width, height)
        return decodeCells(r) { x0, x1, y0, y1 ->
            var sum = 0L
            var n = 0
            for (y in y0 until y1) {
                var p = y * bytesPerRow + x0 * 4
                for (x in x0 until x1) {
                    sum += 54 * (pixels[p + rIdx].toInt() and 0xFF) +
                        183 * (pixels[p + 1].toInt() and 0xFF) +
                        19 * (pixels[p + bIdx].toInt() and 0xFF)
                    n++
                    p += 4
                }
            }
            if (n == 0) 0 else (sum / (256L * n)).toInt()
        }
    }

    /** Reads packed ARGB ints (`Bitmap.getPixels`, `BufferedImage.getRGB`). */
    fun readArgb(
        argb: IntArray,
        width: Int,
        height: Int,
        region: FrameBarcodeRegion? = null,
    ): FrameBarcodeReading {
        require(argb.size >= width * height) { "pixel buffer too small" }
        val r = checkedRegion(region, width, height)
        return decodeCells(r) { x0, x1, y0, y1 ->
            var sum = 0L
            var n = 0
            for (y in y0 until y1) {
                for (x in x0 until x1) {
                    val c = argb[y * width + x]
                    sum += 54 * ((c shr 16) and 0xFF) + 183 * ((c shr 8) and 0xFF) + 19 * (c and 0xFF)
                    n++
                }
            }
            if (n == 0) 0 else (sum / (256L * n)).toInt()
        }
    }

    fun decodeArgb(argb: IntArray, width: Int, height: Int, region: FrameBarcodeRegion? = null): Int? =
        readArgb(argb, width, height, region).index

    private fun checkedRegion(region: FrameBarcodeRegion?, width: Int, height: Int): FrameBarcodeRegion {
        val r = region ?: FrameBarcodeRegion(0, 0, width, height)
        require(r.width >= CELL_COUNT && r.x >= 0 && r.y >= 0 && r.x + r.width <= width &&
            r.y + r.height <= height) { "region $r does not fit a ${width}x$height frame" }
        return r
    }

    /** `meanLuma(x0, x1, y0, y1)` returns the mean 0..255 luma of the pixel box. */
    private fun decodeCells(
        r: FrameBarcodeRegion,
        meanLuma: (Int, Int, Int, Int) -> Int,
    ): FrameBarcodeReading {
        val bandH = bandHeight(r.height)
        val y0 = r.y + bandH / 4
        val y1 = maxOf(r.y + (bandH * 3) / 4, y0 + 1)
        val luma = IntArray(CELL_COUNT)
        for (i in 0 until CELL_COUNT) {
            val cx0 = r.x + i * r.width / CELL_COUNT
            val cx1 = r.x + (i + 1) * r.width / CELL_COUNT
            val cw = cx1 - cx0
            var sx0 = cx0 + cw / 4
            var sx1 = cx1 - cw / 4
            if (sx1 <= sx0) {
                sx0 = cx0
                sx1 = cx1
            }
            luma[i] = meanLuma(sx0, sx1, y0, y1)
        }
        val white = luma[0]
        val black = luma[1]
        val contrast = white - black
        if (contrast <= -MIN_CONTRAST) return FrameBarcodeReading(FrameBarcodeStatus.BAD_GUARD)
        if (contrast < MIN_CONTRAST) return FrameBarcodeReading(FrameBarcodeStatus.NO_SIGNAL)
        val mid = (white + black) / 2.0
        val guard = contrast * MARGIN
        val bits = BooleanArray(CELL_COUNT)
        for (i in 0 until CELL_COUNT) {
            val v = luma[i].toDouble()
            when {
                v > mid + guard -> bits[i] = true
                v < mid - guard -> bits[i] = false
                else -> return FrameBarcodeReading(FrameBarcodeStatus.BLENDED)
            }
        }
        if (!bits[0] || bits[1] || !bits[26] || bits[27]) {
            return FrameBarcodeReading(FrameBarcodeStatus.BAD_GUARD)
        }
        var index = 0
        for (i in 2 until 18) index = (index shl 1) or (if (bits[i]) 1 else 0)
        var crc = 0
        for (i in 18 until 26) crc = (crc shl 1) or (if (bits[i]) 1 else 0)
        if (crc != crc8(index)) return FrameBarcodeReading(FrameBarcodeStatus.BAD_CHECKSUM)
        return FrameBarcodeReading(FrameBarcodeStatus.OK, index)
    }

    /** Paints the band for [index] into an interleaved 4-byte buffer (reader self-tests). */
    fun paint(
        pixels: ByteArray,
        width: Int,
        height: Int,
        index: Int,
        bytesPerRow: Int = width * 4,
        region: FrameBarcodeRegion? = null,
        white: Int = 255,
        black: Int = 0,
    ) {
        val r = region ?: FrameBarcodeRegion(0, 0, width, height)
        val cells = cellsFor(index)
        val bandH = bandHeight(r.height)
        for (i in 0 until CELL_COUNT) {
            val x0 = r.x + i * r.width / CELL_COUNT
            val x1 = r.x + (i + 1) * r.width / CELL_COUNT
            val v = (if (cells[i]) white else black).toByte()
            for (y in r.y until r.y + bandH) {
                var p = y * bytesPerRow + x0 * 4
                for (x in x0 until x1) {
                    pixels[p] = v
                    pixels[p + 1] = v
                    pixels[p + 2] = v
                    pixels[p + 3] = 0xFF.toByte()
                    p += 4
                }
            }
        }
    }
}
