name: vwish_platform
description: Native window management, file pickers, sleep prevention, and custom title bars.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.8
  wakelock_plus: ^1.2.8
  file_selector: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
